server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/bank?serverTimezone=UTC
    username: root
    password: 237066
  redis:
    database: 0
    host: 47.97.120.52
    port: 6379
    timeout: 1200

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.watson.bank.mybatis.entity